---
# Source: ops-repo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prometheus
  labels:
    app: demo-prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-prometheus
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: demo-prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - demo-prometheus
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        - name: demo-prometheus
          image: "registry.cn-hangzhou.aliyuncs.com/gitops-demo/demo-prometheus:20-202503121532-20-fbe9d0c"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 3072Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
      volumes:
        - hostPath:
            path: /etc/localtime
          name: host-time
