---
# Source: ops-repo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-prometheus
  labels:
    app: demo-prometheus
spec:
  ports:
    - port: 
      targetPort: 
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: demo-prometheus
