---
# Source: ops-repo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: xsk-mall-erp
  labels:
    app: xsk-mall-erp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: xsk-mall-erp
